"""add presentation_id to imageasset

Revision ID: 80058fbdf8b8
Revises: fd2ab04834cc
Create Date: 2026-03-19 15:04:24.255539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '80058fbdf8b8'
down_revision: Union[str, None] = 'fd2ab04834cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imageasset', sa.Column('presentation_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_imageasset_presentation_id'), 'imageasset', ['presentation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_imageasset_presentation_id'), table_name='imageasset')
    op.drop_column('imageasset', 'presentation_id')
    # ### end Alembic commands ###
